### ISSUE TITLE
Antigen quite broken with new autosuggest install mechanism

### ISSUE THREAD

**Issue by Gaffney** [zsh-users/antigen#102] opened 2014-12-29 06:54 UTC
Couple of related issues all regarding the [install script](https://github.com/tarruda/zsh-autosuggestions/blob/master/install) that antigen now relies on...

- [This issue on zsh-autosuggestions](https://github.com/tarruda/zsh-autosuggestions/issues/38). Not really antigen's problem, but kind of is at the same time since your guys' installation relies on this.
   
  *I worked around this by installing coreutils and changing it from `readlink` to `greadlink` (see [this SO post](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac))*

- Refer to lines [13-29 of that install script](https://github.com/tarruda/zsh-autosuggestions/blob/master/install#L13-29).  It appends those 14 lines to ~/.zshrc **every time the terminal opens**.

**Comment by sharat87** [comment] 2015-05-12 09:49
Sorry for the delay in responding. I'm not sure I understand what the problem is here. Antigen doesn't rely on any installation script, nothing that I'm aware of anyway.

**Comment by desyncr** [comment] 2015-12-28 15:08
No updates since 2014. I'm closing this for now. @Gaffney feel free to re-open if you have anything to comment on.

**Closed by desyncr** 2015-12-28 15:08 UTC
