### ISSUE TITLE
Extremely slow (>50 seconds) start-up with antigen

### ISSUE THREAD

**Issue by rherrick** [zsh-users/antigen#359] opened 2016-12-11 21:31 UTC
This started a while back but has gotten to the point where zsh with antigen is unusable for me. It takes nearly a minute for a new zsh shell to start up. Most of this time is spent in compdump. I tried to narrow it down to a particular plugin, but at this point I have a line to load antigen and antigen apply.

The output .zcompdump is huge, so that's probably what's causing the issue, but I don't really understand why it's so huge or what's going on with it.

* [.zcompdump](https://github.com/zsh-users/antigen/files/644809/zcompdump.txt)
* [zprof.txt](https://github.com/zsh-users/antigen/files/644811/zprof.txt)
* [.zshrc](https://github.com/zsh-users/antigen/files/644810/zshrc.txt)

I'm using zsh 5.2 and antigen 1.3.0 on OS X 10.12.1 with iTerm2 3.0.12.

Any help would be greatly appreciated. Please let me know if you need any more info to help analyze this issue. Thanks!

**Comment by desyncr** [comment] 2016-12-11 21:46
More than a second from version 1.1.0 and up is clearly a sign something is very wrong.

We've maintaining startup time below a second. There are some stats in the wiki.

It happened to me that zcompdump was appeding stuff to it on every startup. I don't remember the reason thou.
Did you tried to clear your compdup? antigen reset would do it. Otherwise  rm $HOME/.zcompdump*

I'll be taking a further look later today.

**Comment by rherrick** [comment] 2016-12-11 22:00
Not sure if it was the antigen reset or removing the zcompdump file(s) (although I'd deleted the zcompdump.HostName.xxxx files previously, I don't think I'd deleted .zcompdump itself), but that cleared it up. I now get:

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         878.57   878.57   43.84%    789.90   789.90   39.42%  zcache-load-cache
 2)    1         359.26   359.26   17.93%    359.26   359.26   17.93%  compdump
 3)    2         740.49   370.25   36.95%    210.20   105.10   10.49%  compinit
 4)    1         161.08   161.08    8.04%    161.08   161.08    8.04%  -zcache-unhook-antigen
 5)  752         130.28     0.17    6.50%    130.28     0.17    6.50%  compdef
...
```

That gets compdump down to a reasonable level. Thanks for the help and let me know if I can do anything to help figure out what causes that to happen.

**Comment by desyncr** [comment] 2016-12-12 01:10
Thank you for reporting. We'll keep an eye on the issue.

I'm closing this for now as the issue is solved.

**Closed by desyncr** 2016-12-12 01:10 UTC
