### ISSUE TITLE
"antigen theme" command in .zshrc not updating theme

### ISSUE THREAD

**Issue by guixxx** [zsh-users/antigen#483] opened 2017-04-08 17:02 UTC
I'm kinda new to ZSH customization, so I don't know if I'm doing something wrong. I'm so sorry if this is not the right place to ask this.

My `.zshrc`:

```zsh
DEFAULT_USER="${USER}"
DISABLE_AUTO_UPDATE='true'

source /usr/share/zsh/share/antigen.zsh

antigen use oh-my-zsh

case ${TERM} in
    # Use Powerlevel9k if our terminal support 256 colors
    xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
        POWERLEVEL9K_INSTALLATION_PATH="${HOME}/.antigen/bundles/bhilburn/powerlevel9k"
        POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
        POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
        POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
        POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context dir rbenv vcs)
        POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(root_indicator background_jobs command_execution_time time)
        POWERLEVEL9K_STATUS_VERBOSE=false
        POWERLEVEL9K_MODE='nerdfont-fontconfig'

        # For testing purposes only
	echo 'using "powerlevel9k" theme'
        antigen theme bhilburn/powerlevel9k powerlevel9k
    ;;
    # Use a simpler theme if our terminal doesn't support 256 colors
    *)
        # For testing purposes only
	echo 'using "evan" theme'
        antigen theme robbyrussell/oh-my-zsh themes/evan
    ;;
esac

antigen bundle robbyrussell/oh-my-zsh plugins/catimg
antigen bundle robbyrussell/oh-my-zsh plugins/gitfast
antigen bundle robbyrussell/oh-my-zsh plugins/jsontools
antigen bundle robbyrussell/oh-my-zsh plugins/urltools
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply
```

Basically, I'm trying to use the `evan` theme when I login into a virtual console and `Powerlevel9k` on my graphical terminal (`xfce4-terminal`). Unfortunately, it's not working for me. I made a video showing the behavior:

https://www.youtube.com/watch?v=t5m3z8o2wok

Am I doing something wrong or is this an antigen issue? Any help is appreciated. Thank you!

```
Arch Linux x64
XFCE 4.12 (xfce4-terminal)
zsh 5.3.1
Antigen develop
```

**Comment by desyncr** [comment] 2017-04-08 17:09
This happens because Antigen compiles bundles to avoid loading them each time a terminal launches.

**Comment by guixxx** [comment] 2017-04-08 17:13
I see. So is there any workaround for this at the moment? Thanks for quickly answering me.

**Comment by desyncr** [comment] 2017-04-08 17:38
Yes, you could use `ANTIGEN_CACHE` to configure each branch with an alternative cache file:

```sh
case ${TERM} in
    xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
        ANTIGEN_CACHE=$HOME/.antigen/init-xterm.zsh
    ;;
    *)
        ANTIGEN_CACHE=$HOME/.antigen/init-other.zsh
    ;;
esac
```

Please note this has to be done _before_ sourcing Antigen.

**Comment by desyncr** [comment] 2017-04-08 17:39
We're gonna add an option to skip cache generation, probably for `2.0.1`, as we are currently on a release :)

**Comment by guixxx** [comment] 2017-04-08 17:49
Thank you very much!

**Comment by desyncr** [comment] 2017-04-08 19:17
Closing for now. Thanks for reporting the issue. :+1:

**Closed by desyncr** 2017-04-08 19:17 UTC
Labels: Question

**Comment by iamkarlson** [comment] 2017-04-18 19:18
What do you think maybe a good place for this information at the most top of the readme? It's completely unexpected behaviour.

**Comment by desyncr** [comment] 2017-04-18 19:38
Sounds good. In 2.1.0 it should not be a problem as Antigen will auto-detect it's configuration. 

Nevertheless it should be clearly stated how Antigen loads its configs. I'm open to suggestions.

**Comment by iamkarlson** [comment] 2017-04-19 05:24
@desyncr please review #514
