### ISSUE TITLE
Issue while loading antigen.zsh

### ISSUE THREAD

**Issue by eloo** [zsh-users/antigen#488] opened 2017-04-10 08:59 UTC
Hi,
i'm facing an issue with latest antigen version. The problem is that it seems that antigen is not loading properly. My init scripts are throwing "command not found: antigen".
I'm loading antigen like this:
`# Load Antigen
[ ! -f ~/dotfiles/antigen.zsh ] && wget 'https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh' -O ~/dotfiles/antigen.zsh
echo "load antigen"
source $HOME/dotfiles/antigen.zsh
if ! type antigen > /dev/null; then
	echo "antigen not found"
	source $HOME/dotfiles/antigen.zsh
fi`

as you see i've already inserted a check if antigen is available but when i'm creating a new session antigen needs to be loaded twice :/

Antigen: 2.0.0
ZSH: 5.2
OS: macOS 10.12.3

Is anyone facing the same issue? Is there a solution that i'm able to remove the double load of antigen?

Thanks for your help
Eloo

**Comment by desyncr** [comment] 2017-04-10 12:03
It seems to work locally. Same Antigen and zsh version.

**Comment by Eloo** [comment] 2017-04-10 12:35
okay.. i've tested some more things and it seems that the issue is not always reproducible.
But i've noticed that my env variables (e.g. for powerlevel9k theme) are not always been set or recognized.. and antigen reset fixes the problem.. :/

**Comment by desyncr** [comment] 2017-04-10 12:55
If your [dotfiles](https://github.com/Eloo/dotfiles/blob/master/.antigen) reflects what you're testing right now I should note that `antigen apply` goes _after_ all `antigen bundle` commands. Usually at the end of the `.antigenrc` files.

**Comment by desyncr** [comment] 2017-04-10 12:57
Take a look at our [quick start](https://github.com/zsh-users/antigen/wiki/Quick-start#configure-zshrc) guide for a minimal `.zshrc`/`.antigenrc` example.

**Comment by Eloo** [comment] 2017-04-10 13:16
yes the dotfiles from my repo are nearly update... just done some little changes
okay i moved antigen apply to end of my .zshrc so its now at the very end of rc files.
now i see the red cross which indicates an error during a command..
but i don't see any further output :/

**Comment by desyncr** [comment] 2017-04-10 14:07
Yes, it seems Antigen throws a 1 return code. It's not an error.

I'll look later tonight how can this be avoided. Thanks for reporting!

**Comment by Eloo** [comment] 2017-04-10 14:41
okay thanks for your help
if you need more information please let me know

**Comment by Eloo** [comment] 2017-04-11 12:25
I noticed some new "issues" will loading antigen.
It seems that i have to set
`export POWERLEVEL9K_INSTALLATION_PATH="/Users/<username>/.antigen/bundles/bhilburn/powerlevel9k"
`
and 
`export ZSH=$HOME/.antigen/bundles/robbyrussell/oh-my-zsh`

further after i resource my .zshrc my powerlevel9k customizations are gone :/

**Comment by desyncr** [comment] 2017-04-11 12:42
It works for me with this minimal configuration:

```
# Should go first
antigen use oh-my-zsh

# These configs should go _before_ `antigen theme`
POWERLEVEL9K_INSTALLATION_PATH=$HOME/.antigen/bundles/bhilburn/powerlevel9k/
#POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"  

POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='cyan'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_STATUS_VERBOSE=false
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_left"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

antigen theme bhilburn/powerlevel9k powerlevel9k

# Should be last
antigen apply

```

Does it work for you?

**Comment by Eloo** [comment] 2017-04-11 12:53
nope.. facing the same issues.
if I enable my font it will not work when i fork a new terminal (unless i do antigen reset)
and if i'm source my .zshrc a second time (reload for example) the theme no more be applied in new terminals :/

**Comment by desyncr** [comment] 2017-04-11 13:47
Please provide a minimal `.zshrc`/`.antigenrc` where you face this issue.

**Comment by Eloo** [comment] 2017-04-12 06:48
Hi if i you the following .zshrc i'm facing the following issues.
`source dotfiles/antigen.zsh
# Should go first
antigen use oh-my-zsh

# These configs should go _before_ `antigen theme`
POWERLEVEL9K_INSTALLATION_PATH=$HOME/.antigen/bundles/bhilburn/powerlevel9k/
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='cyan'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_STATUS_VERBOSE=false
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_left"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

antigen theme bhilburn/powerlevel9k powerlevel9k

# Should be last
antigen apply`

Following issues appear
* Icons for OS, Folder, git state are gone (font)
 -> Works on first terminal, all new terminals are without icons. (Can be fixed with 'antigen reset' for the next terminal)
* Whole theme is gone if i do 'source .zshrc' and open a new terminal. (Can be fixed with 'antigen reset')
* New terminals are getting the red state cross (return code not 0 i guess?)

I hope you can reproduce my issues too and more fix them :D

best regards
Eloo

**Comment by desyncr** [comment] 2017-04-12 11:23
Thanks for the detailed report. Gonna try to reproduce it. :+1:

**Comment by AdrienHorgnies** [comment] 2017-04-29 01:50
Able to reproduce with the following :
```zsh
export TERM="xterm-256color"
export ZSH=/home/adrien/.oh-my-zsh
DEFAULT_USER="adrien"

source ~/.antigen.zsh

# framework
antigen use oh-my-zsh

# default repo
antigen bundle git
antigen bundle globalias # todo it doesn't WORK :-s
# others
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jhipster/jhipster-oh-my-zsh-plugin

# theme
POWERLEVEL9K_MODE='awesome-fontconfig' # doesn't work either
antigen theme https://github.com/bhilburn/powerlevel9k powerlevel9k

antigen apply
```
I can however "fix" it with `antigen reset` for the next terminal (only the next one, the second one will have the same problem) or I can source `.zshrc` again so the current terminal will work (and only this one, another tab won't work). I'm using xterm with xfce4-terminal.

**Comment by desyncr** [comment] 2017-04-29 02:36
Thanks for the report. I'm gonna take a look!

**Comment by desyncr** [comment] 2017-04-29 03:12
@AdrienHorgnies @Eloo I believe currently (in `develop`) Antigen eagerly loads cache at sourcing (ie, at `source antigen.zsh`) rather than at `antigen apply`. So what is happening is that the theme is loaded before `POWERLEVEL9K_MODE` is set (remember Antigen loads it at sourcing).

A workaround would be to move:

    POWERLEVEL9K_MODE='awesome-fontconfig'

*Before* sourcing Antigen.

This will be resolved in the next version (`2.1.0`).

Sorry for the delay in getting into it.

**Comment by Eloo** [comment] 2017-04-29 11:43
Thanks for your investigation.
WIll try your workaround next week. 
Also looking forward to the fixed version ;)
Thanks for your help!

**Comment by desyncr** [comment] 2017-05-14 22:26
Should be fixed in current release (`v2.1.0`). Closing for now, comment if issue still persists.

**Comment by Eloo** [comment] 2017-05-15 08:53
updated to v2.1.0 and it seems that i still need to use the workaround :/
but with this workaround it seems to work. the only thing i'm facing is that if i open a new terminal and exit it in the next moment i'm receiving an "broken pipe" error.

**Comment by Eloo** [comment] 2017-09-09 14:35
i guess this could be closed
I'm not facing this issue anymore with version 2.2.1

**Comment by desyncr** [comment] 2017-11-16 20:02
@eloo Currently Antigen defers sourcing cache to the `antigen-apply` command. So you may set up env variables before this command and they will be recognised. There is a gotcha regarding `antigen-init`, which is that it's ignored and not parsed/source if there is cache available.

All in all your original issue should be solved :)

**Closed by desyncr** 2017-11-16 20:02 UTC
Labels: Question
